import type { InitiativePack } from "./types";

/**
 * AI initiative governance for healthcare payers. Triage, routing and the
 * fast lane are ported one-for-one from Jeeves (lib/triage/rules.ts,
 * lib/triage/routing.ts, lib/approval/eligibility.ts), and so is the
 * review-time control catalog (lib/demo/reference-data.ts). The
 * equivalence tests prove both.
 *
 * 1.1.0 adds the control catalog.
 */
export const healthcareAiPack: InitiativePack = {
  kind: "initiative",
  id: "healthcare-ai",
  version: "1.1.0",
  title: "Healthcare AI initiatives",
  summary: "Risk tiers and review routing for AI that touches members, PHI, or care and coverage decisions.",
  frameworkRefs: ["NIST AI RMF 1.0", "HIPAA Privacy Rule", "ISO/IEC 42001", "EU AI Act (Annex III)"],
  questions: [
    { field: "phi", label: "Does it use protected health information?", help: "Any PHI, including de-identified data that could be re-identified." },
    { field: "memberFacing", label: "Will members see or interact with it?", help: "Chat, letters, portals, or anything a member receives." },
    { field: "careCoverageInfluence", label: "Could it influence care or coverage decisions?", help: "Prior auth, claims, care management, eligibility." },
    { field: "humanInLoop", label: "Does a person review every output before it takes effect?", help: "A qualified person, not spot checks." },
    { field: "vendorHosted", label: "Is the model or service hosted by a vendor?", help: "Any third-party API or SaaS." },
    { field: "individualImpact", label: "Could it materially affect an individual?", help: "Money, access, health, or reputation." },
  ],
  domains: {
    legal: "Legal",
    procurement: "Procurement",
    "tech-architecture": "Tech Architecture",
    "responsible-ai": "Responsible AI",
    security: "Security",
    "privacy-hipaa": "Privacy / HIPAA",
    "clinical-safety": "Clinical Safety",
    "data-governance": "Data Governance",
  },
  triage: {
    tierRules: [
      {
        id: "care-without-human",
        when: { all: [{ yes: "careCoverageInfluence" }, { not: { yes: "humanInLoop" } }] },
        tier: "critical",
        because: "influences care or coverage with no person reviewing each output",
      },
      {
        id: "care-with-human",
        when: { all: [{ yes: "careCoverageInfluence" }, { yes: "humanInLoop" }] },
        tier: "high",
        because: "influences care or coverage, with a person reviewing each output",
      },
      { id: "phi", when: { yes: "phi" }, tier: "high", because: "uses protected health information" },
      {
        id: "member-impact",
        when: { all: [{ yes: "memberFacing" }, { yes: "individualImpact" }] },
        tier: "high",
        because: "member-facing and can materially affect individuals",
      },
      { id: "individual-impact", when: { yes: "individualImpact" }, tier: "medium", because: "can materially affect individuals" },
      { id: "member-facing", when: { yes: "memberFacing" }, tier: "medium", because: "members see or interact with it" },
    ],
    defaultTier: "low",
    baseDomains: {
      low: ["data-governance", "security"],
      medium: ["data-governance", "security", "tech-architecture", "responsible-ai", "legal"],
      high: ["data-governance", "security", "tech-architecture", "responsible-ai", "legal"],
      critical: [
        "legal",
        "procurement",
        "tech-architecture",
        "responsible-ai",
        "security",
        "privacy-hipaa",
        "clinical-safety",
        "data-governance",
      ],
    },
    domainRules: [
      { when: { yes: "phi" }, add: ["privacy-hipaa"], because: "uses PHI" },
      { when: { yes: "vendorHosted" }, add: ["procurement", "legal"], because: "vendor-hosted" },
      { when: { yes: "careCoverageInfluence" }, add: ["clinical-safety"], because: "influences care or coverage" },
    ],
  },
  fastLane: {
    policyId: "healthcare-ai/fast-lane/v1",
    accountableApprover: "VP, AI Governance",
    maxTier: "low",
    disqualifiers: [
      { when: { yes: "phi" }, reason: "initiative touches PHI" },
      { when: { yes: "memberFacing" }, reason: "initiative is member-facing" },
      { when: { yes: "careCoverageInfluence" }, reason: "initiative influences care or coverage decisions" },
    ],
  },
  controls: [
    {
      id: "L-01",
      domain: "legal",
      name: "Vendor contract AI addendum",
      requiredEvidence: "Signed addendum",
      enforcement: "gate",
      cadence: "Once",
      when: { yes: "vendorHosted" },
      frameworkRefs: ["NIST AI RMF: Govern"],
    },
    {
      id: "L-02",
      domain: "legal",
      name: "Marketing-claims review",
      requiredEvidence: "Approved copy log",
      enforcement: "monitor",
      cadence: "Quarterly",
      when: { yes: "memberFacing" },
      frameworkRefs: ["CMS Medicare Communications and Marketing Guidelines"],
    },
    {
      id: "P-01",
      domain: "procurement",
      name: "Vendor risk assessment",
      requiredEvidence: "Vendor risk assessment",
      enforcement: "gate",
      cadence: "Annual",
      when: { yes: "vendorHosted" },
      frameworkRefs: ["NIST AI RMF: Govern", "HIPAA Security Rule §164.308(b)"],
    },
    {
      id: "P-02",
      domain: "procurement",
      name: "SaaS data-residency attestation",
      requiredEvidence: "Attestation",
      enforcement: "monitor",
      cadence: "Annual",
      when: { yes: "vendorHosted" },
      frameworkRefs: ["NIST AI RMF: Govern"],
    },
    {
      id: "T-01",
      domain: "tech-architecture",
      name: "Architecture review record",
      requiredEvidence: "Architecture review minutes",
      enforcement: "gate",
      cadence: "Once, and on material change",
      when: { all: [] },
      minTier: "medium",
      frameworkRefs: ["NIST AI RMF: Map", "ISO/IEC 42001"],
    },
    {
      id: "T-02",
      domain: "tech-architecture",
      name: "Disaster-recovery plan",
      requiredEvidence: "DR test log",
      enforcement: "monitor",
      cadence: "Annual",
      when: { all: [] },
      minTier: "high",
      frameworkRefs: ["HIPAA Security Rule §164.308(a)(7)"],
    },
    {
      id: "R-01",
      domain: "responsible-ai",
      name: "Bias and fairness testing",
      requiredEvidence: "Test report",
      enforcement: "gate",
      cadence: "Semi-annual",
      when: { any: [{ yes: "memberFacing" }, { yes: "careCoverageInfluence" }] },
      frameworkRefs: ["NIST AI RMF: Measure", "45 CFR §92.210 (ACA Section 1557)"],
    },
    {
      id: "R-02",
      domain: "responsible-ai",
      name: "Model card published",
      requiredEvidence: "Model card",
      enforcement: "monitor",
      cadence: "On version change",
      when: { all: [] },
      minTier: "medium",
      frameworkRefs: ["NIST AI RMF: Map", "ISO/IEC 42001"],
    },
    {
      id: "S-01",
      domain: "security",
      name: "Penetration test or threat model",
      requiredEvidence: "Report",
      enforcement: "gate",
      cadence: "Annual",
      when: { all: [] },
      minTier: "high",
      frameworkRefs: ["NIST AI RMF: Manage", "HIPAA Security Rule §164.308(a)(1)"],
    },
    {
      id: "S-02",
      domain: "security",
      name: "Secrets and access review",
      requiredEvidence: "Access matrix",
      enforcement: "monitor",
      cadence: "Quarterly",
      when: { all: [] },
      frameworkRefs: ["HIPAA Security Rule §164.312(a)(1)"],
    },
    {
      id: "H-01",
      domain: "privacy-hipaa",
      name: "PHI minimization and BAA",
      requiredEvidence: "DPIA and BAA",
      enforcement: "gate",
      cadence: "Once, and on data change",
      when: { yes: "phi" },
      frameworkRefs: ["HIPAA Privacy Rule §164.502(b)", "HIPAA Privacy Rule §164.504(e)"],
    },
    {
      id: "H-02",
      domain: "privacy-hipaa",
      name: "De-identification validation",
      requiredEvidence: "Validation report",
      enforcement: "gate",
      cadence: "Annual",
      when: { all: [{ yes: "phi" }, { yes: "vendorHosted" }] },
      frameworkRefs: ["HIPAA Privacy Rule §164.514(b)"],
    },
    {
      id: "C-01",
      domain: "clinical-safety",
      name: "Clinician-in-the-loop protocol",
      requiredEvidence: "Signed protocol",
      enforcement: "gate",
      cadence: "Once",
      when: { yes: "careCoverageInfluence" },
      frameworkRefs: ["NIST AI RMF: Manage"],
    },
    {
      id: "C-02",
      domain: "clinical-safety",
      name: "Adverse-event monitoring",
      requiredEvidence: "Incident log",
      enforcement: "monitor",
      cadence: "Continuous",
      when: { yes: "careCoverageInfluence" },
      frameworkRefs: ["NIST AI RMF: Manage"],
    },
    {
      id: "D-01",
      domain: "data-governance",
      name: "Data lineage and sourcing approval",
      requiredEvidence: "Lineage document",
      enforcement: "gate",
      cadence: "Once, and on data change",
      when: { all: [] },
      minTier: "medium",
      frameworkRefs: ["NIST AI RMF: Map", "ISO/IEC 42001"],
    },
    {
      id: "D-02",
      domain: "data-governance",
      name: "Retention and disposal schedule",
      requiredEvidence: "Schedule",
      enforcement: "monitor",
      cadence: "Annual",
      when: { yes: "phi" },
      frameworkRefs: ["HIPAA Security Rule §164.310(d)(2)"],
    },
  ],
};
